name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    branches: [ "master" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      # checkout repo
    - name: checkout
      uses: actions/checkout@v3
      
    - name: setup-dotnet
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x
